# Generated by Django 5.1.3 on 2024-11-23 08:29

import CarDekho.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDekho', '0002_carlist_chassisnumber_carlist_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroomlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='carlist',
            name='chassisnumber',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[CarDekho.models.alphanumeric]),
        ),
    ]
